# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180307_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbinary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
