# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20180307_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbinary',
            old_name='projectName',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='projectsrc',
            old_name='projectName',
            new_name='filename',
        ),
    ]
