# Generated by Django 2.0 on 2018-05-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20180307_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbinary',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectsrc',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
